#!/usr/bin/env python3
"""FluxGen Pipeline - MOCK VERSION for testing UI/webhooks"""
import os, sys, json, time, subprocess, requests
from pathlib import Path

MAX_LOOPS = int(os.getenv('MAX_LOOPS', '2'))  # Fewer loops for testing
CALLBACK_URL = os.getenv('CALLBACK_URL', '')
PROJECT_ID = os.getenv('PROJECT_ID', '')
STEP_DELAY = int(os.getenv('STEP_DELAY', '30'))  # Seconds per step

def log(msg):
    print(msg, flush=True)

def send_webhook(status, message, agent=None, phase=None, loop_number=None):
    if not CALLBACK_URL or not PROJECT_ID: return
    payload = {'projectId': PROJECT_ID, 'status': status, 'message': message}
    if agent: payload['agent'] = agent
    if phase: payload['phase'] = phase
    if loop_number: payload['loopNumber'] = loop_number
    try:
        resp = requests.post(CALLBACK_URL, json=payload, timeout=10, allow_redirects=True)
        resp.raise_for_status()
        log(f"[Webhook] {agent or 'system'}: {message}")
    except Exception as e:
        log(f"[Webhook] FAILED: {e}")

def simulate_work(agent_name, duration=None):
    """Simulate work with a delay"""
    delay = duration or STEP_DELAY
    log(f"  [{agent_name}] Simulating work for {delay} seconds...")
    time.sleep(delay)
    log(f"  [{agent_name}] Done!")

def write_file(path, content):
    path.write_text(content)
    log(f"  [Mock] Created {path.name}")

def run_marc_planning(root, prd):
    log("\n" + "="*60 + "\n📋 MARC - Planning (MOCK)\n" + "="*60)
    send_webhook('marc_plan', "Creating implementation plan...", 'marc', 'marc_plan', 1)

    simulate_work('marc')

    # Create mock PLAN.md
    plan_content = f"""# Implementation Plan

## Project: {prd.get('project_name', 'Test Project')}

### Overview
{prd.get('description', 'A test project')}

### Tech Stack
- Next.js 14
- TypeScript
- Tailwind CSS

### File Structure
```
./
├── package.json
├── next.config.js
├── src/
│   ├── app/
│   │   ├── page.tsx
│   │   └── layout.tsx
│   └── components/
│       └── Header.tsx
└── public/
```

### Implementation Steps
1. Create package.json with dependencies
2. Set up Next.js configuration
3. Create main page component
4. Add styling with Tailwind
5. Test the application

### User Stories
{json.dumps(prd.get('stories', []), indent=2)}

---
*Generated by FluxGen Mock Pipeline*
"""
    write_file(root / 'PLAN.md', plan_content)

    send_webhook('marc_plan', "Plan ready!", 'marc', 'marc_plan', 1)
    return True, plan_content

def run_jake_build(root, prd, plan, loop, qa_fb=""):
    log(f"\n{'='*60}\n👨‍💻 JAKE - Building (Loop {loop}) (MOCK)\n{'='*60}")
    send_webhook('jake_build', "Building..." if loop == 1 else "Fixing issues...", 'jake', 'jake_build', loop)

    simulate_work('jake')

    # Create mock package.json
    package_json = {
        "name": prd.get('project_name', 'test-project').lower().replace(' ', '-'),
        "version": "1.0.0",
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "lint": "next lint"
        },
        "dependencies": {
            "next": "14.0.0",
            "react": "18.2.0",
            "react-dom": "18.2.0"
        }
    }
    write_file(root / 'package.json', json.dumps(package_json, indent=2))

    # Create mock src directory and files
    src_app = root / 'src' / 'app'
    src_app.mkdir(parents=True, exist_ok=True)

    write_file(src_app / 'page.tsx', f'''export default function Home() {{
  return (
    <main>
      <h1>{prd.get('project_name', 'Test Project')}</h1>
      <p>Built by FluxGen Mock Pipeline</p>
    </main>
  )
}}
''')

    write_file(src_app / 'layout.tsx', '''export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
''')

    send_webhook('jake_build', "Build done!", 'jake', 'jake_build', loop)
    return True

def run_doug_verify(root, loop):
    log(f"\n{'='*60}\n🔧 DOUG - Verifying (Loop {loop}) (MOCK)\n{'='*60}")
    send_webhook('doug_verify', "Verifying build...", 'doug', 'doug_verify', loop)

    simulate_work('doug')

    # Create mock BUILD_LOG.md
    build_log = f"""# Build Log - Loop {loop}

## Files Found
- package.json
- src/app/page.tsx
- src/app/layout.tsx
- PLAN.md

## npm install
✅ Simulated success

## npm run build
✅ Simulated success

## Dev Server Test
✅ Server started on port 5555 (simulated)

---
*Generated by FluxGen Mock Pipeline*
"""
    write_file(root / 'BUILD_LOG.md', build_log)

    send_webhook('doug_verify', "Verified!", 'doug', 'doug_verify', loop)
    return True

def run_cody_qa(root, prd, loop):
    log(f"\n{'='*60}\n🧪 CODY - QA (Loop {loop}) (MOCK)\n{'='*60}")
    send_webhook('cody_qa', "Testing...", 'cody', 'cody_qa', loop)

    simulate_work('cody')

    # Create mock QA_REPORT.md - pass on loop 2, fail on loop 1
    if loop >= 2:
        qa_report = f"""# QA Report - Loop {loop}

## Summary: PASS ✅
All tests pass! The implementation meets all requirements.

## Critical Issues
None

## High Issues
None

## Medium Issues
None

## Low Issues
- Consider adding more responsive styles

## Story Verification
{json.dumps(prd.get('stories', []), indent=2)}

All user stories verified! ✅

---
*Generated by FluxGen Mock Pipeline*
"""
    else:
        qa_report = f"""# QA Report - Loop {loop}

## Summary: NEEDS WORK

## Critical Issues
None

## High Issues
- Missing proper error handling in page.tsx

## Medium Issues
- No loading states implemented
- Missing meta tags

## Low Issues
- Could use more comments

## Story Verification
{json.dumps(prd.get('stories', []), indent=2)}

---
*Generated by FluxGen Mock Pipeline*
"""

    write_file(root / 'QA_REPORT.md', qa_report)

    send_webhook('cody_qa', "QA done!", 'cody', 'cody_qa', loop)
    return True, qa_report

def run_marc_review(root, qa_report, loop):
    log(f"\n{'='*60}\n📋 MARC - Reviewing (Loop {loop}) (MOCK)\n{'='*60}")
    send_webhook('marc_review', "Reviewing QA...", 'marc', 'marc_review', loop)

    simulate_work('marc', duration=15)  # Shorter for review

    # Update PLAN.md with fixes
    plan = (root / 'PLAN.md').read_text() if (root / 'PLAN.md').exists() else ""
    updated_plan = plan + f"""

---
## Fixes for Loop {loop + 1}

Based on QA feedback:
1. Add error handling to page.tsx
2. Implement loading states
3. Add meta tags for SEO

---
*Updated by FluxGen Mock Pipeline*
"""
    write_file(root / 'PLAN.md', updated_plan)

    send_webhook('marc_review', "Plan updated!", 'marc', 'marc_review', loop)
    return True, updated_plan

def run_connor_docs(root, prd, loop):
    log(f"\n{'='*60}\n📝 CONNOR - Docs (MOCK)\n{'='*60}")
    send_webhook('connor_docs', "Writing docs...", 'connor', 'connor_docs', loop)

    simulate_work('connor')

    name = prd.get('project_name', 'Test Project')
    desc = prd.get('description', 'A test project')

    readme = f"""# {name}

{desc}

## Features
- Modern Next.js 14 application
- TypeScript support
- Tailwind CSS styling

## Tech Stack
- Next.js 14
- React 18
- TypeScript
- Tailwind CSS

## Installation

```bash
npm install
```

## Development

```bash
npm run dev
```

Open [http://localhost:3000](http://localhost:3000) in your browser.

## Build

```bash
npm run build
npm start
```

---
*Built with FluxGen Mock Pipeline*
"""

    how_to_run = f"""# How to Run {name}

## Prerequisites
- Node.js 18+
- npm or yarn

## Setup

1. Clone the repository
2. Install dependencies:
   ```bash
   npm install
   ```

## Development

Run the development server:
```bash
npm run dev
```

## Production

Build and start:
```bash
npm run build
npm start
```

## Troubleshooting

- If port 3000 is in use, Next.js will try the next available port
- Clear `.next` folder if you encounter build issues

---
*Generated by FluxGen Mock Pipeline*
"""

    write_file(root / 'README.md', readme)
    write_file(root / 'How_to_run.md', how_to_run)

    send_webhook('connor_docs', "Docs done!", 'connor', 'connor_docs', loop)
    return True

def should_continue(qa_report):
    low = qa_report.lower()
    if 'all pass' in low or 'all tests pass' in low:
        return False, "All passing"
    if 'critical' in low or 'high' in low:
        return True, "Issues to fix"
    return False, "No blocking issues"

def main():
    root = Path.cwd()
    prd_path = root / 'prd.json'

    log("🚀 FluxGen Pipeline (MOCK MODE - No AI APIs)")
    log(f"   ⏱️  Step delay: {STEP_DELAY} seconds")
    log(f"   🔄 Max loops: {MAX_LOOPS}")

    if not prd_path.exists():
        log("❌ prd.json not found, creating mock PRD...")
        mock_prd = {
            "project_name": "Test Project",
            "description": "A test project for UI development",
            "mode": "scratch",
            "tech_stack": "Next.js",
            "stories": [
                {"title": "User can view homepage", "description": "Basic homepage display"},
                {"title": "User can navigate", "description": "Navigation works correctly"}
            ]
        }
        prd_path.write_text(json.dumps(mock_prd, indent=2))

    prd = json.loads(prd_path.read_text())

    # Phase 1: Planning
    ok, plan = run_marc_planning(root, prd)
    if not ok:
        log("❌ Planning failed")
        sys.exit(1)

    # Phase 2: Build loops
    final_loop = 1
    complete = False
    qa_feedback = ""

    for loop in range(1, MAX_LOOPS + 1):
        final_loop = loop
        log(f"\n🔄 LOOP {loop}/{MAX_LOOPS}")
        send_webhook('loop_iteration', f"Loop {loop}", 'marc', 'loop_start', loop)

        # Build
        run_jake_build(root, prd, plan, loop, qa_feedback)

        # Verify
        run_doug_verify(root, loop)

        # QA
        _, qa_report = run_cody_qa(root, prd, loop)

        # Check if we should continue
        cont, reason = should_continue(qa_report)
        log(f"  [QA] {reason}")

        if not cont:
            complete = True
            break

        # Review and update plan for next iteration
        if loop < MAX_LOOPS:
            _, plan = run_marc_review(root, qa_report, loop)
            qa_feedback = qa_report

    # Phase 3: Documentation
    run_connor_docs(root, prd, final_loop)

    # Final status
    status = 'completed' if complete else 'blocked'
    message = "Done!" if complete else "Needs attention"
    send_webhook(status, message, 'connor', 'complete', final_loop)

    # Git commit
    log("\n📦 Committing changes...")
    subprocess.run(['git', 'config', 'user.email', 'fluxgen@example.com'], cwd=str(root))
    subprocess.run(['git', 'config', 'user.name', 'FluxGen Bot'], cwd=str(root))
    subprocess.run(['git', 'add', '-A'], cwd=str(root))
    result = subprocess.run(
        ['git', 'commit', '-m', 'feat: FluxGen implementation (MOCK)'],
        cwd=str(root), capture_output=True, text=True
    )
    log(f"[Git] {result.stdout} {result.stderr}")

    log("\n✅ Mock Pipeline complete!" if complete else "\n⚠️ Mock Pipeline needs attention")

if __name__ == '__main__':
    main()
